unstable_features = true
blank_lines_lower_bound = 0
combine_control_expr = false
comment_width = 80
condense_wildcard_suffixes = true
enum_discrim_align_threshold = 20
error_on_line_overflow = true
error_on_unformatted = false
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
max_width = 100
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
