[package]
name = "rml-proc-dummy"
authors = ["Daniel Drodt <daniel.drodt@tu-darmstadt.de>"]
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.22", features = ["printing"] }
rml-syn = { path = "../rml-syn" }
